# Generated by Django 5.0.2 on 2024-12-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_skill_created_at_remove_skill_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='User_profile',
            new_name='user_profile',
        ),
    ]
