# Generated by Django 5.0.2 on 2024-12-12 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_rename_user_profile_skill_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.userprofile'),
        ),
    ]
