# Generated by Django 5.0.2 on 2024-12-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_skill_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='Users.skill'),
        ),
    ]
