# Generated by Django 5.0.2 on 2024-12-12 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_skill_name_alter_skill_user_profile_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='user_profile',
        ),
    ]
